AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template to create a Security Group

Parameters:
  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: The ID of the VPC where the security group will be created.

  IngressCidr:
    Type: String
    Default: 0.0.0.0/0
    Description: CIDR range for ingress traffic. Default is open to all.

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Allow specific ingress and egress traffic
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref IngressCidr
          Description: Allow SSH traffic
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: !Ref IngressCidr
          Description: Allow HTTP traffic
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref IngressCidr
          Description: Allow HTTPS traffic
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic

Outputs:
  SecurityGroupId:
    Description: The ID of the created Security Group
    Value: !Ref SecurityGroup
